### PR TITLE
Adopt upstream version 0.6

### PR DESCRIPTION
**Pull request by paulvonallwoerden**
**Summary**

The upstream repository has evolved a lot since this fork has been created and now supports all features we added natively. Therefore this PR will bring this fork to the state of the upstream. Only a few small changes were made.

- A type for WorkflowRuns was added to achieve type safety.
- The README.md was adapted to be closer to the current version of our readme.

### CODE REVIEW

**Comment by fixpunkt** [comment]
But do we still need the fork just for type safety?

**Comment by svenmuennich** [comment]
> But do we still need the fork just for type safety?

Should we maybe send a PR containing your fixes to the upstream repository instead?

**Comment by paulvonallwoerden** [comment]
I see. I thought we would maintain this fork to have our own copy of the code. If this is indeed not the reason, then I definitely think Sven's suggestion is right. I will then open a PR against the upstream and archive this repository, since we don't have to make our own adjustments anymore.

**Comment by fixpunkt** [comment]
Sounds like a plan. But what exactly is even still left to upstream?

**Comment by paulvonallwoerden** [comment]
We have the option to make small improvements like ensuring type safety upstream. But in fact there are no functional changes. So maybe we should just do without the extra effort and use the upstream as it is.

**Comment by paulvonallwoerden** [comment]
We decided against this fork. The decision has been made at https://github.com/pickware/pickware-cloud/issues/722. If the maintainers of our other repositories agree and all actions have been updated to use the upstream instead, this fork can been deleted.

See the discussion on Slack for more information: https://pickware.slack.com/archives/C47RBTFD0/p1605089557006000

**Pull request closed without merging**
